# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mactop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/metaspartan/mactop"
  version "2.0.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/metaspartan/mactop/releases/download/v2.0.0/mactop_2.0.0_darwin_arm64.tar.gz"
    sha256 "cb3e462a450b5cb45798617acfa70315487fb84421d7b9af5335de4e35825823"

    def install
      bin.install "mactop"
    end
  end

  def caveats
    <<~EOS
      mactop requires macOS 12+, and runs exclusively on Apple Silicon.
    EOS
  end
end
